kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker


-----------------

kind create cluster --name rajan --config=kindcluster.yaml

kind delete cluster --name=raman

kubectl config view 

kubectl config view | grep kind

kubectl config use-context rajan

